import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';

import './globals.css';

import Footer from './components/UI/Footer';
import Navbar from './components/UI/Navbar';
import PagePadding from './components/UI/PagePadding';

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
      >
        <Navbar />
        <PagePadding>
          {children}
        </PagePadding>
        <Footer />
      </body>
    </html>
  );
}
